### ISSUE TITLE
Adjust export script once/if bug 1631932 lands.

### ISSUE THREAD

**Issue by miketaylr** [mozilla-extensions/webcompat-addon#138]
The location of output is changing in m-c, so we'll have to update our jake export script accordingly: https://bugzilla.mozilla.org/show_bug.cgi?id=1631932

@denschub can you take care of this once it lands?

**Comment by miketaylr** [comment]
Also, it looks like we need to update the addon version in BrowserGlue.jsm, so it would be nice if the output of the build script could do that for us:

https://phabricator.services.mozilla.com/D75678#change-GJBE8iYGIQVM

**Comment by denschub** [comment]
Do we know if/how this change affects Balrog updates and our testing workflow?

**Comment by miketaylr** [comment]
According to @wisniewskit, it should not. Can you confirm Tom?

**Comment by denschub** [comment]
DId some testing, and everything appears to be fine. That's great. :)

**Comment by denschub** [comment]
It's been a lot of years. Closing.
