### ISSUE TITLE
Backport 3 patch sets from M-C once they land

### ISSUE THREAD

**Issue by miketaylr** [mozilla-extensions/webcompat-addon#145]
https://phabricator.services.mozilla.com/D81750
https://phabricator.services.mozilla.com/D81749

**Comment by denschub** [comment]
Make that three:

https://phabricator.services.mozilla.com/D81594

**Comment by miketaylr** [comment]
> https://phabricator.services.mozilla.com/D81750

https://bugzilla.mozilla.org/show_bug.cgi?id=1649554 has landed. 

>  https://phabricator.services.mozilla.com/D81749

https://bugzilla.mozilla.org/show_bug.cgi?id=1649554 has landed.

> https://phabricator.services.mozilla.com/D81594

https://bugzilla.mozilla.org/show_bug.cgi?id=1649221 has landed.

**Comment by miketaylr** [comment]
https://phabricator.services.mozilla.com/D81749
hg hash:8cf125948dc084e8e9131120f8356f488f3ed774 => git hash: 264b6960156b730070eeb55c3b3b0ca39364f4da

https://phabricator.services.mozilla.com/D81750
hg hash: 53244d442a4f2d9ec40517b6e957ed6e58d3e873 => git hash: 739ab0416b7499553a707b9e19e496d6508f0164

https://phabricator.services.mozilla.com/D81594
hg hash: e3478cefc7b03131e24e4333bb9a196a1282b92f => git hash: b05003294b7d0f1289e176c9cd13f63e220681ac

**Comment by miketaylr** [comment]
OK all done:

https://github.com/mozilla-extensions/webcompat-addon/commit/c1a36071c7f7310d007083fa63e6e39b3bcae82d
https://github.com/mozilla-extensions/webcompat-addon/commit/dd9ffe995cc8b76c263033df23fe010179aae4cf
https://github.com/mozilla-extensions/webcompat-addon/commit/852a3d61b6cff1e35ca9596043969698da0e65fd
