### ISSUE TITLE
Fix bad match pattern in ua_overrides for bug1563839.

### ISSUE THREAD

**Issue by Rob--W** [mozilla-extensions/webcompat-addon#157]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1654524

This is missing a `/`:
https://github.com/mozilla-extensions/webcompat-addon/blob/4f198b02d0beb3765e6003d711aaef50ed2451a2/src/data/ua_overrides.js#L590

Please fix this, and consider adding CI/tests to verify that the patterns are valid.

**Comment by miketaylr** [comment]
Oh yeah, thanks for the bug report @Rob--W.

**Comment by miketaylr** [comment]
@ksy36 can you work on getting a patch landed here, and upstream?

**Comment by miketaylr** [comment]
@ksy36 this is fixed now, right?

**Comment by ksy36** [comment]
Yeah, fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=1654555

**Comment by miketaylr** [comment]
Thanks!

(And https://github.com/mozilla-extensions/webcompat-addon/commit/67dd7435545deb97d8b04aaeee7f6f168ae2496c for the in-addon commit)
