### ISSUE TITLE
Create tests / linting for (in)valid match patterns

### ISSUE THREAD

**Issue by miketaylr** [mozilla-extensions/webcompat-addon#158]
A bad pattern made its way through review, which caused https://bugzilla.mozilla.org/show_bug.cgi?id=1654524 (to be fixed in https://github.com/mozilla-extensions/webcompat-addon/issues/157).

If we can write some tests to fail in CI before landing, that would be ideal.

**Comment by miketaylr** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns are the rules. I'm sure it's not trivial to valid all possible inputs, there's probably some things we can look for:

> `<scheme>://<host><path>`

Do we have a scheme, a host, and a path?

> `<scheme>`

This can be '*' or one of ['http', 'https', 'ws', 'wss', 'ftp', 'ftps', 'data', 'file'].

We probably only care about '*', 'http', 'https'?

> `<host>`

We could validate if there's a '*', that it isn't preceded by anything (assuming we're operating on the host that's been split out from the entire string). It can only be '*', '*.whatever', or 'whatever'.

> `<path>`

> The path component must begin with a /.
> After that, it may subsequently contain any combination of the * wildcard and any of the characters that are allowed in URL paths or query strings. Unlike host, the path component may contain the * wildcard in the middle or at the end, and the * wildcard may appear more than once.

This is more complex, but we can ensure it actually exists. 

For the bug in `"*://*.bancosantander.es*",` if we had some of these rules, `<host>` validation could fail because there are 2 '*'s, which isn't allowed. And `<path>` validation could fail because it doesn't exist (no leading `/`).

There's maybe other tests we could write.

**Comment by miketaylr** [comment]
some naive code to validate against:

```
const pattern = "https://mozilla.org/d/b/f/";
const scheme = pattern.split("://")[0];
const hostPath =  pattern.split("://")[1];
const host = hostPath.split("/").shift();
const path = hostPath.slice(hostPath.indexOf("/"))

> scheme
"https"
> host
mozilla.org
> path
"/d/b/f/"

```

**Comment by Rob--W** [comment]
Here's the regexp that Firefox uses:

https://searchfox.org/mozilla-central/rev/dcd9c2d2bc19d96d487825eb70c2333a4d60994e/toolkit/components/extensions/schemas/manifest.json#542

You can omit ws(s), it's not going to be relevant.

If desired you can also add `<all_urls>` and `file:`, but I guess that these aren't relevant for webcompat.

**Comment by miketaylr** [comment]
Nice, thanks @Rob--W
