### ISSUE TITLE
"about:compat" Enable/Disable entry states don't persist across app restart

### ISSUE THREAD

**Issue by MasterInQuestion** [mozilla-extensions/webcompat-addon#334]
Likely already known issue.
    Similar to: https://bugzilla.mozilla.org/show_bug.cgi?id=1871964

**Comment by denschub** [comment]
This is by design. The toggles are meant for testing for our QA folks, they aren't meant as a user-service to toggle individual interventions.

**Comment by MasterInQuestion** [comment]
Regardless, the real issue is mostly beyond the scope.
    Which I might address when I get the time.
