### ISSUE TITLE
Conflict with "about:config" options

### ISSUE THREAD

**Issue by MasterInQuestion** [mozilla-extensions/webcompat-addon#356]
E.g. "general.appversion.override"
    When testing this:
    [ https://github.com/mozilla-extensions/webcompat-addon/commit/df506ff0f3f66cd948a2825f6f74ca2c2eff7406](https://github.com/mozilla-extensions/webcompat-addon/commit/df506ff0f3f66cd948a2825f6f74ca2c2eff7406)
    .
    [ https://github.com/webcompat/web-bugs/issues/108993](https://github.com/webcompat/web-bugs/issues/108993)
    https://www.samsung.com/in/watches/galaxy-watch/galaxy-watch5-44mm-graphite-bluetooth-sm-r910nzaainu/
    navigator.appVersion
    ; regardless be "5.0 (Linux)".

    Alike may not be the expected behavior.
\
\
    Workaround:
    https://old.reddit.com/r/firefox/comments/17fpe4y/webcompat_shims_vs_injections/?sort=old#k6egfdh
    .
    Setting:
    |&#x2A;| extensions.webcompat.enable_shims: false
    |&#x2A;| extensions.webcompat.perform_injections: false
    |&#x2A;| extensions.webcompat.perform_ua_overrides: false

    See also: [ https://github.com/mozilla-extensions/webcompat-addon/issues/346](https://github.com/mozilla-extensions/webcompat-addon/issues/346)

**Comment by denschub** [comment]
> Alike may not be the expected behavior.

Expected. WebExtensions run after anything inside Firefox. `general.appversion.override` is affecting the default UA, not the final UA.

**Comment by MasterInQuestion** [comment]
Semantically yes.
    Practically, counter-intuitive. (high factor of astonishment)

\
    Does the workaround adequately work?
    (disabling the WebCompat extension outright)
[ ^
    Yes, almost. (turning which mostly no-op; though not strictly disabled)
    Note "extensions.webcompat.perform_ua_overrides" was merged into "injections":
    [https://bugzilla.mozilla.org/show_bug.cgi?id=1945258](https://bugzilla.mozilla.org/show_bug.cgi?id=1945258)
    (so obsolete) ]

    Is &#x60;`"privacy.antitracking.enableWebcompat": false`&#x60; in addition necessary?
[ ^
    That controls more than WebCompat. (also ETP & more)
    Details:
    [https://bugzilla.mozilla.org/show_bug.cgi?id=1683165](https://bugzilla.mozilla.org/show_bug.cgi?id=1683165)
    [https://developer.mozilla.org/en-US/docs/Web/Privacy/Guides/State_Partitioning#disable_web_compatibility_features](https://developer.mozilla.org/en-US/docs/Web/Privacy/Guides/State_Partitioning#disable_web_compatibility_features) ]
