### ISSUE TITLE
Emit a console.warn when doing an override

### ISSUE THREAD

**Issue by nchevobbe** [mozilla-extensions/webcompat-addon#47]
In https://bugzilla.mozilla.org/show_bug.cgi?id=1531509 it was reported that having a console message could help developer understand what's going on.

A console warning could be a good start (the message can be styled to be bigger than other messages if we want that `console.warn("%cThis website has compatibility issues […]", "font-size: 48px;")`).

**Comment by miketaylr** [comment]
And a message encouraging them to look at about:compat (which contains links to the bugs, and allows them to disable the intervention for testing a fix) would be ideal too.
